version: '3'

services:
    db:
      image: 'postgres:13.1-alpine'
      container_name: db
      ports:
        - "5440:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
